{{ range .Values.configFiles }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "amavis.fullname" $ }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
data:
  {{ base .mountPath }}: |-
    {{- .content | nindent 4 -}}
{{- end -}}
