apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "amavis.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "amavis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "amavis.selectorLabels" . | nindent 8 }}
        {{- if .Values.additionalLabels -}}
          {{- toYaml .Values.additionalLabels | nindent 8 }}
        {{- end }}
    {{- if .Values.additionalTemplateSpec -}}
      {{- toYaml .Values.additionalTemplateSpec | nindent 4 }}
    {{- end }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.affinityLabel }}
                operator: In
                values:
                - {{ .Values.environment }}
      {{- if .Values.additionalPodSpec -}}
        {{- toYaml .Values.additionalPodSpec | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: AV_MYDOMAIN
          value: "{{ .Values.defaultDomain }}"
        - name: AV_POSTFIX_SERVICE_NAME
          value: "{{ include "amavis.relayHostname" . }}"
        - name: AV_POSTFIX_SERVICE_PORT
          value: "{{ .Values.relayPort }}"
        - name: AV_VIRUSADMIN_EMAIL
          value: "{{ .Values.virusAdminEmail }}"
        ports:
        - name: amavis
          containerPort: 10024
        volumeMounts:
        - name: virusmails
          mountPath: /var/virusmails
{{- range .Values.configFiles }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          subPath: {{ base .mountPath }}
{{- end }}
        {{- if .Values.additionalContainerSpec -}}
          {{- toYaml .Values.additionalContainerSpec | nindent 8 }}
        {{- end }}
        resources:
            {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: virusmails
        hostPath:
          path: /var/docker/{{ .Release.Name }}/{{ .Values.environment }}/virusmails
{{- range .Values.configFiles }}
      - name: {{ .name }}
        configMap:
          name: {{ include "amavis.fullname" $ }}-{{ .name }}
{{- end }}
