# Default values for a mailserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#####################################################
# General settings valid for all pods
#####################################################
# $affinityLabel - the key of the node label for affinity stickiness
# $environment     - the node label value for key "mailserver/environment" to stick the pod to a certain node in your cluster
# $imagePullPolicy - The image pull policy used in the pods
affinityLabel: &default_affinity_label "mailserver/environment"
environment: &default_environment "production"
imagePullPolicy: &default_pull_policy "IfNotPresent"

# $mariadb.affinityLabel    - the key of the node label for affinity stickiness
# $mariadb.environment      - the node label value for key "mailserver/environment" to stick the pod to a certain node in your cluster
# $mariadb.image            - definition of docker image
# $mariadb.image.repository - the image name (without tag)
# $mariadb.image.pullPolicy - The pull policy for the image
# $mariadb.additionalLabels - additional labels to attach to a pod
# $mariadb.service          - description of the service object
# $mariadb.service.type     - the service type (ClusterIP, NodePort, LoadBalancer)
# $mariadb.service.port     - the port number to expose by the service
# $mariadb.rootPassword     - the password for the root account when initially settig up the DB. ATTENTION! You shall change the password manually after the DB is set up
# $mariadb.bufferPoolSize   - the buffer pool size for InnoDB
# $mariadb.maxAllowedPacket - The maximum size of a packet
# $mariadb.volumeType       - How is the data volume being connected (hostPath, pvc)
# $mariadb.enableAuditLog   - enables the mariadb audit plugin
# $mariadb.auditFilePath    - where to store the audit file (default is the data directory in order to persist automatically)
# $mariadb.additionalTemplateSpec  - Add more deployment template specification at this value
# $mariadb.additionalPodSpec       - Add more pod specification at this value
# $mariadb.additionalContainerSpec - Add more container specification at this value
mariadb:
  affinityLabel: *default_affinity_label
  environment: *default_environment
  rootPassword: "my-db-root-password"
  image:
    pullPolicy: *default_pull_policy

# $postfix.affinityLabel           - the key of the node label for affinity stickiness
# $postfix.environment             - the node label value for key "mailserver/environment" to stick the pod to a certain node in your cluster
# $postfix.image                   - definition of docker image
# $postfix.image.repository        - the image name (without tag)
# $postfix.image.pullPolicy        - The pull policy for the image
# $postfix.additionalLabels        - additional labels to attach to a pod
# $postfix.replicaCount            - the number of replicas in the deployment to create
# $postfix.service.externalIP      - the bind address of your node where services shall listen
# $postfix.service.smtpPort        - SMTP Port
# $postfix.service.pop3Port        - POP3 Port
# $postfix.service.imapPort        - IMAP Port
# $postfix.service.submissionPort  - Submission Port
# $postfix.service.imapsPort       - IMAPS Port
# $postfix.service.pop3sPort       - POP3S Port
# $postfix.service.relayPort       - Relay port for incoming mail scan results (from amavis)
# $postfix.resources               - additional resource requirements
# $postfix.dbHostname              - the database host
# $postfix.dbName                  - the database instance name
# $postfix.dbUser                  - the database user to use
# $postfix.dbPassword              - the password of the database user to use
# $postfix.dbSetupPassword         - the root password for setup
# $postfix.defaultDomain           - default mail domain
# $postfix.serverName              - hostname to be used for HELO greeting
# $postfix.origin                  - default origin of mails, usually default mail domain
# $postfix.amavisHostname          - name of host for Amavis mail scanning (optional)
# $postfix.amavisPort              - relay port for Amavis mail scanning
# $postfix.tlsCertificatePath      - directory where TLS certificate files are stored in the pod
# ==> The following TLS certificate values shall not be set in your values file directly but given as arguments to the HELM command:
# ==> e.g. --set-file postfix.tlsCertificateChain=/path/to/fullchain.pem,postfix.tlsCertificate=/path/to/cert.pem,postfix.tlsKey=/path/to/privkey.pem
# $postfix.tlsCertificateChain     - TLS certificate chain (NOT base64 encoded)
# $postfix.tlsCertificate:         - TLS certificate (NOT base64 encoded)
# $postfix.tlsKey                  - TLS key (NOT base64 encoded)
# $postfix.tlsCAPath               - directory where trusted CA certificates are stored
# $postfix.tlsAdminEmail           - e-mail of admin to be informed when TLS certificate is about to expire
# $postfix.configFiles             - definition of additional config files
# $postfix.additionalTemplateSpec  - Add more deployment template specification at this value
# $postfix.additionalPodSpec       - Add more pod specification at this value
# $postfix.additionalContainerSpec - Add more container specification at this value
postfix:
  affinityLabel: *default_affinity_label
  environment: *default_environment
  image:
    pullPolicy: *default_pull_policy
  service:
    externalIP: "your-external-ip"
  dbPassword: "my-db-postfix-password"
  dbSetupPassword: "my-db-root-password"
  defaultDomain: "my-domain.tld"
  serverName: "my-mailserver"
  origin: "my-domain.tld"
  tlsAdminEmail: "tls-admin@my-domain.tld"
  tlsCertificateChain: ""
  tlsCertificate: ""
  tlsKey: ""

# $amavis.affinityLabel    - the key of the node label for affinity stickiness
# $amavis.environment      - the node label value for key "mailserver/environment" to stick the pod to a certain node in your cluster
# $amavis.image            - definition of docker image
# $amavis.image.repository - the image name (without tag)
# $amavis.image.pullPolicy - The pull policy for the image
# $amavis.additionalLabels - additional labels to attach to a pod
# $amavis.replicaCount     - the number of replicas in the deployment to create
# $amavis.service.port     - the incoming service port
# $amavis.resources        - additional resource requirements
# $amavis.defaultDomain    - default mail domain
# $amavis.relayHostname    - name of host for Amavis mail scanning (optional)
# $amavis.relayPort        - relay port for Amavis mail scanning
# $amavis.virusAdminEmail  - e-mail of admin to be informed when viruses were quarantined
# $amavis.configFiles      - definition of additional config files
# $amavis.additionalTemplateSpec  - Add more deployment template specification at this value
# $amavis.additionalPodSpec       - Add more pod specification at this value
# $amavis.additionalContainerSpec - Add more container specification at this value
amavis:
  affinityLabel: *default_affinity_label
  environment: *default_environment
  image:
    pullPolicy: *default_pull_policy
  defaultDomain: "my-domain.tld"
  virusAdminEmail: "virus-admin@my-domain.tld"


# $postfixadmin.image              - definition of docker image
# $postfixadmin.image.repository   - the image name (without tag)
# $postfixadmin.image.pullPolicy   - The pull policy for the image
# $postfixadmin.additionalLabels   - additional labels to attach to a pod
# $postfixadmin.replicaCount       - the number of replicas in the deployment to create
# $postfixadmin.service.port       - Webserver port to bind the service to
# $postfixadmin.resources          - additional resource requirements
# $postfixadmin.dbHostname         - the database host
# $postfixadmin.dbName             - the database instance name
# $postfixadmin.dbUser             - the database user to use
# $postfixadmin.dbPassword         - the password of the database user to use
# $postfixadmin.mailserverHostname - hostname to be used for HELO greeting
# $postfixadmin.mailserverPort     - relay port for Amavis mail scanning
# $postfixadmin.setupPassword      - the setup password for PostfixAdmin
# $postfixadmin.abuseEmail         - e-mail of abuse admin
# $postfixadmin.hostmasterEmail    - e-mail of host responsible
# $postfixadmin.postmasterEmail    - e-mail of mail responsible
# $postfixadmin.webmasterEmail     - e-mail of web responsible
# $postfixadmin.additionalTemplateSpec  - Add more deployment template specification at this value
# $postfixadmin.additionalPodSpec       - Add more pod specification at this value
# $postfixadmin.additionalContainerSpec - Add more container specification at this value
postfixadmin:
  image:
    pullPolicy: *default_pull_policy
  dbPassword: "my-db-postfix-password"
  setupPassword: "my-pfa-setup-password"
  abuseEmail: "abuse@my-domain.tld"
  hostmasterEmail: "hostmaster@my-domain.tld"
  postmasterEmail: "postmaster@my-domain.tld"
  webmasterEmail: "webmaster@my-domain.tld"


# $roundcube.image              - definition of docker image
# $roundcube.image.repository   - the image name (without tag)
# $roundcube.image.pullPolicy   - The pull policy for the image
# $roundcube.additionalLabels   - additional labels to attach to a pod
# $roundcube.replicaCount       - the number of replicas in the deployment to create
# $roundcube.service.port       - Webserver port to bind the service to
# $roundcube.resources          - additional resource requirements
# $roundcube.dbHostname         - the database host
# $roundcube.dbName             - the database instance name
# $roundcube.dbUser             - the database user to use
# $roundcube.dbPassword         - the password of the database user to use
# $roundcube.imapServerHostname - hostname to be used for HELO greeting
# $roundcube.smtpServerHostname - hostname to be used for HELO greeting
# $roundcube.defaultDomain      - The default domain for login users
# $roundcube.desKey             - a unique 24-char string for your server (required, must not be empty)
# $roundcube.additionalTemplateSpec  - Add more deployment template specification at this value
# $roundcube.additionalPodSpec       - Add more pod specification at this value
# $roundcube.additionalContainerSpec - Add more container specification at this value
roundcube:
  image:
    pullPolicy: *default_pull_policy
  dbPassword: "my-db-roundcube-password"
  defaultDomain: "my-domain.tld"
  desKey: ""

