apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postfix.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "postfix.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postfix.selectorLabels" . | nindent 8 }}
        {{- if .Values.additionalLabels -}}
          {{- toYaml .Values.additionalLabels | nindent 8 }}
        {{- end }}
    {{- if .Values.additionalTemplateSpec -}}
      {{- toYaml .Values.additionalTemplateSpec | nindent 4 }}
    {{- end }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.affinityLabel }}
                operator: In
                values:
                - {{ .Values.environment }}
      {{- if .Values.additionalPodSpec -}}
        {{- toYaml .Values.additionalPodSpec | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: PF_DB_HOST
          value: "{{ include "postfix.dbHostname" . }}"
        - name: PF_DB_NAME
          value: "{{ .Values.dbName }}"
        - name: PF_DB_USER
          value: "{{ .Values.dbUser }}"
        - name: PF_DB_PASS
          value: "{{ .Values.dbPassword }}"
        - name: PF_SETUP_PASS
          value: "{{ .Values.dbSetupPassword }}"
        - name: PF_MYDOMAIN
          value: "{{ .Values.defaultDomain }}"
        - name: PF_MYHOSTNAME
          value: "{{ .Values.serverName }}"
        - name: PF_MYORIGIN
          value: "{{ .Values.origin }}"
        - name: PF_AMAVIS_SERVICE_NAME
          value: {{ include "postfix.amavisHostname" . }}
        - name: PF_AMAVIS_SERVICE_PORT
          value: "{{ .Values.amavisPort }}"
{{- if .Values.tlsCertificate }}
        - name: PF_TLS_CERT_FILE
          value: "{{ .Values.tlsCertificatePath }}/tls.crt"
        - name: PF_TLS_KEY_FILE
          value: "{{ .Values.tlsCertificatePath }}/tls.key"
        - name: PF_TLS_CAFILE
          value: "{{ .Values.tlsCertificatePath }}/tls.chain"
{{- end }}
        - name: PF_TLS_CAPATH
          value: "{{ .Values.tlsCAPath }}"
        - name: PF_TLS_ADMIN_EMAIL
          value: "{{ .Values.tlsAdminEmail }}"
        ports:
        - name: smtp
          containerPort: 25
        - name: pop3
          containerPort: 110
        - name: imap
          containerPort: 143
        - name: submission
          containerPort: 587
        - name: imaps
          containerPort: 993
        - name: pop3s
          containerPort: 995
        - name: amavis
          containerPort: 10025
        volumeMounts:
        - name: mailboxes
          mountPath: /var/vmail
        - name: spool
          mountPath: /var/spool/postfix
{{- if .Values.tlsCertificate }}
        - name: certificate
          mountPath: {{ .Values.tlsCertificatePath }}
{{- end }}
{{- range .Values.configFiles }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          subPath: {{ base .mountPath }}
{{- end }}
        {{- if .Values.additionalContainerSpec -}}
          {{- toYaml .Values.additionalContainerSpec | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: mailboxes
        hostPath:
          path: /var/docker/{{ .Release.Name }}/{{ .Values.environment }}/mailboxes
      - name: spool
        hostPath:
          path: /var/docker/{{ .Release.Name }}/{{ .Values.environment }}/spool
{{- if .Values.tlsCertificate }}
      - name: certificate
        secret:
          secretName: {{ template "postfix.fullname" . }}-certificate
{{- end }}
{{- range .Values.configFiles }}
      - name: {{ .name }}
        configMap:
          name: {{ include "postfix.fullname" $ }}-{{ .name }}
{{- end }}

