apiVersion: v1
kind: Service
metadata:
  name: {{ include "postfix.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: smtp
      port: {{ .Values.service.smtpPort }}
      targetPort: smtp
      protocol: TCP
    - name: pop3
      port: {{ .Values.service.pop3Port }}
      targetPort: pop3
      protocol: TCP
    - name: imap
      port: {{ .Values.service.imapPort }}
      targetPort: imap
      protocol: TCP
    - name: submission
      port: {{ .Values.service.submissionPort }}
      targetPort: submission
      protocol: TCP
    - name: imaps
      port: {{ .Values.service.imapsPort }}
      targetPort: imaps
      protocol: TCP
    - name: pop3s
      port: {{ .Values.service.pop3sPort }}
      targetPort: pop3s
      protocol: TCP
  selector:
    {{- include "postfix.selectorLabels" . | nindent 4 }}
  externalIPs:
  - "{{ .Values.service.externalIP }}"
