apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb
  namespace: mailserver
data:
  mariadb-auth.cnf: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
  mariadb-sizing.cnf: |-
    [mysqld]
    innodb_buffer_pool_size=1024M
    max_allowed_packet=64M
    sql_mode=""
  mariadb-audit-log.cnf: |-
    [mariadb]
    plugin_load_add = server_audit
    server_audit_events = CONNECT,QUERY,TABLE
    server_audit_logging = ON
    server_audit_file_path = /var/lib/mysql/server_audit.log
